/**
 * 
 */
package com.keystone.common.utils;

/**
 * @author nnarayanaperumaln
 *
 */
public enum ErrorCodes {

	MEDIA_TYPE_NOT_SUPPORTED,
	MESSAGE_NOT_READABLE,
	SERVLET_BINDING_EXCEPTION,
	INTERNAL_SERVICE_ERROR,
	
	VALIDATION_ERROR_CODE,
	
    METHOD_ARGUMENT_TYPE_MISMATCH,

    PAYLOAD_TYPE_EMPTY,
    PAYLOAD_TYPE_INVALID,
    CHARACTOR_ENTERED_TOO_LONG,


    PAYLOAD_INVALID,
    PAYLOAD_SOURCE_INVALID,
    PAYLOAD_USER_INVALID,
    APP_TYPE_HEADER_INVALID,
    GENERIC_EXCEPTION,
    UNAUTHORIZED,
    PRECONDITION_FAILED,
    

	
	//
	NOT_FOUND, 
	DATA_MISMATCH;
    
}
